# Generated by Django 2.0.4 on 2018-04-03 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptics', '0002_auto_20180402_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='likers',
            field=models.ManyToManyField(related_name='clues_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
