# Generated by Django 2.0.4 on 2018-04-05 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptics', '0004_auto_20180403_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='winning_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_this_won', to='cryptics.Submission'),
        ),
        migrations.AddField(
            model_name='contest',
            name='winning_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
