# Generated by Django 2.0.4 on 2018-04-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptics', '0006_auto_20180418_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='active',
        ),
    ]
