# Generated by Django 2.0.4 on 2021-01-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptics', '0007_remove_contest_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='word',
            field=models.CharField(max_length=150),
        ),
    ]
