# Generated by Django 5.0.6 on 2024-06-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptics', '0008_auto_20210113_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['created_at']},
        ),
    ]
